import React from "react";

export const metadata: { title: string; description: string } = {
  title: "Default Template",
  description: "Generated by create next app",
};

export function layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}

export default layout;
